In [1]:
!pip install numpy 

import numpy as np

print("Numpy version:", np.__version__)

Numpy version: 2.3.0


Exercice 1

In [2]:


array_1d = np.arange(10) 
print(array_1d)


[0 1 2 3 4 5 6 7 8 9]


Exercice 2

In [3]:

my_list = [3.14, 2.17, 0, 1, 2]

array_float = np.array(my_list)


array_int = array_float.astype(int)

print(array_int)


[3 2 0 1 2]


Exercice 3

In [4]:

array_1_to_9 = np.arange(1, 10)


matrix_3x3 = array_1_to_9.reshape(3, 3)

print(matrix_3x3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


Exercice 4

In [5]:

random_array = np.random.rand(4, 5)

print(random_array)


[[0.27593332 0.89531469 0.60072201 0.41714424 0.76729253]
 [0.89959518 0.3694703  0.06207984 0.63088947 0.60069261]
 [0.01222038 0.52682528 0.81423909 0.67307594 0.09747491]
 [0.06666913 0.45089549 0.01841484 0.89417568 0.11727513]]


Exercice 5

In [6]:
array = np.array([[21, 22, 23, 22, 22],
                  [20, 21, 22, 23, 24],
                  [21, 22, 23, 22, 22]])

second_row = array[1]  
print(second_row)


[20 21 22 23 24]


Exercice 6

In [7]:
array = np.arange(10)

reversed_array = array[::-1]
print(reversed_array)


[9 8 7 6 5 4 3 2 1 0]


Exercice 7

In [8]:
identity_matrix = np.eye(4)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Exercice 8

In [9]:
array = np.arange(10)

total = np.sum(array)
average = np.mean(array)

print("Sum:", total)
print("Average:", average)


Sum: 45
Average: 4.5


Exercice 9

In [10]:
array = np.arange(1, 21)

reshaped_array = array.reshape(4, 5)

print(reshaped_array)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Exercice 10

In [11]:
array = np.arange(10)

odd_numbers = array[array % 2 != 0]
print(odd_numbers)


[1 3 5 7 9]


In [ ]:
!git add .
!git commit -m "Analyse des données de vente et profitabilité"
!git push origin main